#!/bin/bash

#atlas_submit_cube_m mh0-300 308000 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357

#atlas_submit_cube_m mh0-hyd 230777 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357
#atlas_submit_cube_m mh0-hyd 233100 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357
#atlas_submit_cube_m mh0-hyd 235427 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357

#atlas_submit_cube_m mh0-ssd 237495 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357
#atlas_submit_cube_m mh0-ssd 244258 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357
#atlas_submit_cube_m mh0-ssd 251568 mh0 flux.input.mh0 mpsa.control.mh0_odf 1357

#atlas_submit_cube_m mh1-300 182000 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357

#atlas_submit_cube_m mh1-hyd 004661 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357
#atlas_submit_cube_m mh1-hyd 007049 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357
#atlas_submit_cube_m mh1-hyd 009383 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357

#atlas_submit_cube_m mh1-ssd 536452 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357
#atlas_submit_cube_m mh1-ssd 542081 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357
#atlas_submit_cube_m mh1-ssd 547390 mh1 flux.input.mh1 mpsa.control.mh1_odf 1357



#------------------------------------------------------------------------------

atlas_submit_hk_m mh0-300 308000 1357

atlas_submit_hk_m mh0-hyd 230777 1357
atlas_submit_hk_m mh0-hyd 233100 1357
atlas_submit_hk_m mh0-hyd 235427 1357

atlas_submit_hk_m mh0-ssd 237495 1357
atlas_submit_hk_m mh0-ssd 244258 1357
atlas_submit_hk_m mh0-ssd 251568 1357

atlas_submit_hk_m mh1-300 182000 1357

atlas_submit_hk_m mh1-hyd 004661 1357
atlas_submit_hk_m mh1-hyd 007049 1357
atlas_submit_hk_m mh1-hyd 009383 1357

atlas_submit_hk_m mh1-ssd 536452 1357
atlas_submit_hk_m mh1-ssd 542081 1357
atlas_submit_hk_m mh1-ssd 547390 1357
