#!/bin/sh

# parsed by qsub (-v option)
# run
# atm
# flog
# slog
# spec
# rangl

# when this line is uncommented the result of every command
# is logged in standard error files ($lde in atlas_submit_cube_m)
#set -x

module load intel-suite
module load netcdf/4.0.1-mcmodel-medium

base=/rds/general/user/rtagirov/ephemeral/runs/atlas

# for each individual job a temporary directory is created
# with its name stored in the $TMPDIR variable
# in this directory the calculations are performed
# after the calculations are done the directory is removed
tmp=$TMPDIR

mkdir -p $tmp/INPUT

cd $tmp/INPUT

ln -s $base/$run/INPUT/* ./

cd -
cd $tmp

ln -s $base/$run/mpsa.control ./
ln -s $base/$run/run-mpsa.x   ./

cd -

declare -i flat angle slice

declare -i next_angle

flat=$PBS_ARRAY_INDEX

angle=flat/512
slice=flat%512

if ((slice == 0)); then angle=angle-1; slice=512; fi

next_angle=angle+1

mu=${rangl:angle:1}

mu_next=${rangl:next_angle:1}

if [ $mu = 1 ]; then

    if [ $mu_next = 0 ]; then

        mu=10

    fi

fi

sid="$mu,$slice"

dir=$base/$run/groups/$mu/$slice

if [ -d $dir ]; then rm -r $dir; fi

mkdir -p $dir

ln -s /rds/general/user/rtagirov/ephemeral/cubes/metallicity/$atm/$mu/atms/atlas/$slice $tmp/INPUT/flux.model

/usr/bin/time -v $tmp/run-mpsa.x > $tmp/atlas.log 2>&1

cp -P $tmp/INPUT/flux.model $dir

rm -f $tmp/mpsa.jnu
rm -f $tmp/mpsa.print

#rsync -arq --no-links $tmp/ $dir/
#rsync -aq --no-links --no-dirs --no-recursive $tmp/ $dir/
rsync -aq --no-links --no-dirs $tmp/ $dir/

if [ ! -s $dir/atlas.log ]; then echo "$sid: no log" >> $flog; fi

if [ -s $dir/atlas.log ]; then

    ok=$(grep 'O.K.' $dir/atlas.log)

    sp=$(grep 'No space left on device' $dir/atlas.log)

    ma=$(grep 'malloc(): corrupted top size' $dir/atlas.log)

    if [ ! "$ok" ] && [ ! "$sp" ] && [ ! "$ma" ]; then echo "$sid: reason unknown" >> $flog; fi

    if [ "$sp" ]; then echo "$sid: no space left on device" >> $flog; fi

    if [ "$ma" ]; then echo "$sid: malloc corrupted top size" >> $flog; fi

    if [ "$ok" ]; then

        echo $sid: >> $slog

        mv $dir/mpsa.punch $spec/$mu.$slice

        if ((flat == 1)); then mv $dir/fort.41 $spec/mpsa.wave; fi
        if ((flat != 1)); then rm $dir/fort.41; fi

    fi

fi

rm -r $dir/INPUT

module purge
