#!/bin/bash

cubes='mh0-hyd/230777 mh0-hyd/233100 mh0-hyd/235427
       mh1-hyd/004661 mh1-hyd/007049 mh1-hyd/009383
       mh0-ssd/237495 mh0-ssd/244258 mh0-ssd/251568
       mh1-ssd/536452 mh1-ssd/542081 mh1-ssd/547390
       mh0-300/308000
       mh1-300/182000'

for cube in $cubes; do

   IFS='/' read -r -a array <<< "$cube"

   nohup python met_spec_eff_parallel_3D.py $cube > ./log/log.${array[0]}.${array[1]} & 
#   nohup python met_spec_eff_parallel.py $cube > ./log/log.${array[0]}.${array[1]} & 

done
