#!/bin/sh

if [ $# != 5 ]; then
 
   echo expecting 5 arguments: stype, ctype, rname, rangl, apath
 
   exit 1
 
fi

stype=$1
ctype=$2
rname=$3
rangl=$4
apath=$5

declare -i Na Ns Nt

Na=${#rangl}
Ns=512
Nt=Na*Ns

walltime=24:00:00

base=/rds/general/user/rtagirov/ephemeral/runs/atlas

run=$stype/matthias/$ctype/$rfrac/$rname/$rangl
atm=$stype/matthias/$ctype/$apath

bin=$HOME/atlas/bin
exe=$bin/run-mpsa.x
inp=$HOME/atlas/inp_flux

ldo=$HOME/log/atlas/$run/out
lde=$HOME/log/atlas/$run/err

slog=$base/$run/success.log
flog=$base/$run/fail.log
spec=$base/$run/spec

mkdir -p $base/$run $ldo $lde

if [ -d $base/$run/INPUT ];        then rm -r $base/$run/INPUT;        fi
if [ -f $base/$run/mpsa.control ]; then rm -f $base/$run/mpsa.control; fi

mkdir -p $base/$run/INPUT

echo Submitting $run:

echo Copying input files...

cp $inp/nessy_odf.bdf $base/$run/INPUT
cp $inp/molecules.dat $base/$run/INPUT
cp $inp/flux.input    $base/$run/INPUT
cp $inp/mpsa.control  $base/$run

echo Removing old spectra...

rm -r    $spec
mkdir -p $spec

echo Removing old logs...

rm $slog
rm $flog
rm $ldo/*
rm $lde/*

cp $exe $base/$run

IFS='/' read -r -a array <<< "$run"

name=a:${ctype:0:1}/$rname/$rangl

qsub -v \
run=$run,\
atm=$atm,\
slog=$slog,\
flog=$flog,\
spec=$spec,\
rangl=$rangl \
-J 1-$Nt:1 \
-o $ldo \
-e $lde \
-N $name \
-lwalltime=$walltime \
-lselect=1:ncpus=1:mem=2gb:avx2=true atlas_calc_slice_spec
